using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;

namespace Silksong.AssetHelper.BundleTools.Repacking;

/// <summary>
/// Base class for repacking strategies.
/// </summary>
public abstract class SceneRepacker
{
    /// <summary>
    /// Generate sensible cab and bundle names for the given bundle.
    /// 
    /// These don't matter, but the ones generated by this function look like the ones made by unity.
    /// </summary>
    protected static void GetDefaultBundleNames(
        string sceneBundlePath,
        List<string> objectNames,
        string outBundlePath,
        out string cabName,
        out string bundleName)
    {
        const string salt = "AssetHelperSalt\n";

        using SHA256 sha256 = SHA256.Create();

        StringBuilder inputSb = new();
        inputSb.AppendLine(salt);
        inputSb.AppendLine(sceneBundlePath ?? string.Empty);

        foreach (string name in objectNames)
        {
            inputSb.AppendLine($"\n{name}");
        }

        inputSb.AppendLine(outBundlePath);

        string saltedInput = inputSb.ToString();

        byte[] inputBytes = Encoding.UTF8.GetBytes(saltedInput);
        byte[] hashBytes = sha256.ComputeHash(inputBytes);

        StringBuilder sb = new(64);
        foreach (byte b in hashBytes)
        {
            sb.Append(b.ToString("x2"));
        }

        string fullHash = sb.ToString();

        cabName = $"CAB-{fullHash.Substring(0, 32)}";
        bundleName = $"{fullHash.Substring(32, 32)}.bundle";
    }

    /// <inheritdoc cref="Repack(string, List{string}, string, ref RepackedBundleData)" />
    public RepackedBundleData Repack(
        string sceneBundlePath,
        List<string> objectNames,
        string outBundlePath
        )
    {
        RepackedBundleData outData = new();

        GetDefaultBundleNames(sceneBundlePath, objectNames, outBundlePath, out string cabName, out string bundleName);
        outData.CabName = cabName;
        outData.BundleName = bundleName;

        Repack(sceneBundlePath, objectNames, outBundlePath, ref outData);
        return outData;
    }

    /// <summary>
    /// Create a bundle that can be used to spawn objects from the provided scene bundle.
    /// </summary>
    /// <param name="sceneBundlePath">A path to the scene bundle.</param>
    /// <param name="objectNames">A list of game objects to include.
    /// Any game object in this list should have an ancestor which is accessible via <see cref="UnityEngine.AssetBundle.LoadAsset(string)"/>,
    /// provided the supplied game object exists in the bundle.</param>
    /// <param name="outBundlePath">File location for the repacked bundle.</param>
    /// <param name="outData">The RepackedBundleData object describing the generated bundle. Some properties (such as cab/bundle name)
    /// will be read from this parameter; the repacking function will populate others.</param>
    public abstract void Repack(
        string sceneBundlePath,
        List<string> objectNames,
        string outBundlePath,
        ref RepackedBundleData outData);
}
